"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class flow_entry_t(object):
    __slots__ = ["src_addr", "dst_addr", "pkt_count", "byte_count", "data_rate", "last_activity"]

    def __init__(self):
        self.src_addr = ""
        self.dst_addr = ""
        self.pkt_count = 0
        self.byte_count = 0
        self.data_rate = 0.0
        self.last_activity = 0

    def encode(self):
        buf = BytesIO()
        buf.write(flow_entry_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __src_addr_encoded = self.src_addr.encode('utf-8')
        buf.write(struct.pack('>I', len(__src_addr_encoded)+1))
        buf.write(__src_addr_encoded)
        buf.write(b"\0")
        __dst_addr_encoded = self.dst_addr.encode('utf-8')
        buf.write(struct.pack('>I', len(__dst_addr_encoded)+1))
        buf.write(__dst_addr_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">iidq", self.pkt_count, self.byte_count, self.data_rate, self.last_activity))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != flow_entry_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return flow_entry_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = flow_entry_t()
        __src_addr_len = struct.unpack('>I', buf.read(4))[0]
        self.src_addr = buf.read(__src_addr_len)[:-1].decode('utf-8', 'replace')
        __dst_addr_len = struct.unpack('>I', buf.read(4))[0]
        self.dst_addr = buf.read(__dst_addr_len)[:-1].decode('utf-8', 'replace')
        self.pkt_count, self.byte_count, self.data_rate, self.last_activity = struct.unpack(">iidq", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if flow_entry_t in parents: return 0
        tmphash = (0x8dec104c036eb71e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if flow_entry_t._packed_fingerprint is None:
            flow_entry_t._packed_fingerprint = struct.pack(">Q", flow_entry_t._get_hash_recursive([]))
        return flow_entry_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

