"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import rnp.flow_entry_t

class flow_list_t(object):
    __slots__ = ["addr", "timestamp", "n", "flows"]

    def __init__(self):
        self.addr = ""
        self.timestamp = 0
        self.n = 0
        self.flows = []

    def encode(self):
        buf = BytesIO()
        buf.write(flow_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __addr_encoded = self.addr.encode('utf-8')
        buf.write(struct.pack('>I', len(__addr_encoded)+1))
        buf.write(__addr_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">qi", self.timestamp, self.n))
        for i0 in range(self.n):
            assert self.flows[i0]._get_packed_fingerprint() == rnp.flow_entry_t._get_packed_fingerprint()
            self.flows[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != flow_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return flow_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = flow_list_t()
        __addr_len = struct.unpack('>I', buf.read(4))[0]
        self.addr = buf.read(__addr_len)[:-1].decode('utf-8', 'replace')
        self.timestamp, self.n = struct.unpack(">qi", buf.read(12))
        self.flows = []
        for i0 in range(self.n):
            self.flows.append(rnp.flow_entry_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if flow_list_t in parents: return 0
        newparents = parents + [flow_list_t]
        tmphash = (0x6ef608367e97358b+ rnp.flow_entry_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if flow_list_t._packed_fingerprint is None:
            flow_list_t._packed_fingerprint = struct.pack(">Q", flow_list_t._get_hash_recursive([]))
        return flow_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

