#!/bin/bash


# some default parameters #
NODEID=1
TXPOWER=20
CHANNEL=1
WLAN=wlan19
CLICKSCRIPT=/root/click_scripts/rnp_scripts/rnp_linux_args_aligned.click
INITROUTES=""

print_help()
{
    echo "setup_manet: xxxx"
}
export -f print_help


while [ $# -gt 0 ]
do
    key="$1"
    case $key in
	-n|---node-id)
	    NODEID="$2"
	    shift # past argument
	    ;;
	-p|--power)
	    TXPOWER="$2"
	    shift # past argument
	    ;;
	-c|--channel)
	    CHANNEL="$2"
	    shift # past argument
	    ;;
	-i|--interface)
	    WLAN="$2"
	    shift
	    ;;
	-s|--click-script)
	    CLICKSCRIPT="$2"
	    shift
	    ;;
	-r|--init-routes)
	    INITROUTES="$2"
	    shift
	    ;;
	-h|--help)
	    print_help
	    exit
	    shift
	    ;;
	*)
            # unknown option
	    print_help
	    exit
	    ;;
    esac
    shift # past argument or value
done

echo "using:"
echo "NODEID=${NODEID}"
echo "TXPOWER=${TXPOWER}"
echo "CHANNEL=${CHANNEL}"
echo "WLAN=${WLAN}"



IPPREFIX=10.42.43
NETMASK=24

IPADDR=${IPPREFIX}.${NODEID}
WLANM=`cat /sys/class/net/${WLAN}/address`
#echo ${WLANM}


setup_wlan ${WLAN} ${IPADDR}/${NETMASK} ${CHANNEL} ${TXPOWER} 

ip route del to ${IPPREFIX}.0/${NETMASK}

CTIME=$(env TZ=":Europe/Rome" date +%Y%m%d_%H%M%S)
export CTIME

CLICKLOGFILE="/logs/${CTIME}-click.log"
CLICKCURRENTLOG="/logs/click.log"

cd /logs && RNP_PKGclick WLANMAC=${WLANM} WLANINTERFACE=${WLAN} ADHOCIP=${IPADDR}/${NETMASK} ${CLICKSCRIPT} &> ${CLICKLOGFILE} &
ln -f -s ${CLICKLOGFILE} ${CLICKCURRENTLOG}
sleep 5
if [ -n "${INITROUTES}" ]; then
    echo "sending default routes ..."
    python -m publish_route2_tree -c RNP2 ${IPADDR} `cat ${INITROUTES} | tr '\n' ' '`
fi
read -p "Press any key to finish"

echo "Finished."


   

