"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class route2_entry_t(object):
    __slots__ = ["dest", "node", "weight"]

    def __init__(self):
        self.dest = ""
        self.node = ""
        self.weight = 0

    def encode(self):
        buf = BytesIO()
        buf.write(route2_entry_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __dest_encoded = self.dest.encode('utf-8')
        buf.write(struct.pack('>I', len(__dest_encoded)+1))
        buf.write(__dest_encoded)
        buf.write(b"\0")
        __node_encoded = self.node.encode('utf-8')
        buf.write(struct.pack('>I', len(__node_encoded)+1))
        buf.write(__node_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">h", self.weight))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != route2_entry_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return route2_entry_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = route2_entry_t()
        __dest_len = struct.unpack('>I', buf.read(4))[0]
        self.dest = buf.read(__dest_len)[:-1].decode('utf-8', 'replace')
        __node_len = struct.unpack('>I', buf.read(4))[0]
        self.node = buf.read(__node_len)[:-1].decode('utf-8', 'replace')
        self.weight = struct.unpack(">h", buf.read(2))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if route2_entry_t in parents: return 0
        tmphash = (0x6f99f508e62603c3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if route2_entry_t._packed_fingerprint is None:
            route2_entry_t._packed_fingerprint = struct.pack(">Q", route2_entry_t._get_hash_recursive([]))
        return route2_entry_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

